# Generated by Django 4.1.5 on 2023-02-21 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('quartier', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('credit', models.FloatField(blank=True, max_length=15)),
                ('note', models.FloatField(blank=True, max_length=15)),
                ('appreciation', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('naissance', models.DateTimeField(verbose_name='date de naisssance')),
                ('genre', models.CharField(choices=[('M', 'masculin'), ('F', 'feminin'), ('Autre', 'autre')], max_length=32)),
                ('nationalite', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_app.personne')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('grade', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
                ('type_poste', models.CharField(max_length=50)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.adresse')),
                ('matiere', models.ManyToManyField(to='student_app.matiere')),
            ],
            bases=('student_app.personne',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_app.personne')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('filiere', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Nouveau', 'nouveau'), ('Ancien', 'ancien')], max_length=32)),
                ('niveau', models.CharField(choices=[('L1', 'licence 1'), ('L2', 'licence 2'), ('L3', 'licence 3')], max_length=32)),
                ('regime', models.CharField(choices=[('RN', 'normal'), ('RS', 'spécial')], max_length=15)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.adresse')),
                ('matiere', models.ManyToManyField(to='student_app.matiere')),
            ],
            bases=('student_app.personne',),
        ),
    ]
