# Generated by Django 4.1.5 on 2023-02-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='matiere',
            new_name='Matiere',
        ),
        migrations.RenameField(
            model_name='personne',
            old_name='nationalite',
            new_name='nationnalite',
        ),
        migrations.AlterField(
            model_name='adresse',
            name='quartier',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='ville',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.adresse', unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], max_length=32),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='regime',
            field=models.CharField(choices=[('Special', 'Special'), ('Normal', 'Normal')], max_length=15),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('Ancien', 'Ancien'), ('Nouveau', 'Nouveau')], max_length=32),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='appreciation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='personne',
            name='genre',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=32),
        ),
        migrations.AlterField(
            model_name='personne',
            name='naissance',
            field=models.DateTimeField(verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/photo'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='grade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='matricule',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='type_poste',
            field=models.CharField(max_length=100),
        ),
    ]
